import 'package:hive_flutter/hive_flutter.dart';

// The `part` directive tells Dart that journal_entry.g.dart belongs here.
// This file is auto-generated by build_runner — do NOT edit it manually.
part 'journal_entry.g.dart';

/// The core data entity for a single journal entry.
///
/// typeId: 0 — unique identifier for Hive to know which adapter to use.
/// Each field has a unique HiveField index (never change these after first use
/// or existing stored data will break).
///
/// Future: when Clean Architecture layers are added, this model will be
/// separated into a domain Entity (pure Dart) and a Data Model (Hive-aware).
@HiveType(typeId: 0)
class JournalEntry extends HiveObject {
  @HiveField(0)
  final String id;

  /// Index into kMoodOptions list (0=Rough, 1=Low, 2=Okay, 3=Good, 4=Great)
  @HiveField(1)
  final int moodIndex;

  @HiveField(2)
  final String note;

  @HiveField(3)
  final DateTime date;

  JournalEntry({
    required this.id,
    required this.moodIndex,
    required this.note,
    required this.date,
  });
}
